name: qingyu
description: "A flutter project integrates varies of efficient utility tools"
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.10.7

dependencies:
    flutter:
        sdk: flutter
    crypto: ^3.0.3
    shared_preferences: ^2.2.2
    qr_flutter: ^4.1.0
    flutter_screenutil: ^5.9.0
    get: ^4.6.6
    path_provider: ^2.1.3
    image: ^4.2.0
    permission_handler: ^11.3.1
    web: ^0.5.1
    file_picker: ^8.0.0+1
    convert: ^3.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true
