name: qingyu
description: "A flutter project integrates varies of efficient utility tools"
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.10.7

dependencies:
    flutter:
        sdk: flutter
    crypto: ^3.0.3
    shared_preferences: ^2.2.2
    qr_flutter: ^4.1.0
    flutter_screenutil: ^5.9.0
    get: ^4.6.6
    path_provider: ^2.1.3
    image: ^4.2.0
    permission_handler: ^11.3.1
    web: ^1.1.0
    file_picker: ^8.0.0+1
    convert: ^3.1.2
    flutter_launcher_icons: ^0.14.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true

flutter_launcher_icons:
    android: "launcher_icon"
    # ios: true
    image_path: "web/icons/icon.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
        generate: true
        image_path: "web/icons/icon.png"
        background_color: "#hexcode"
        theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "path/to/image.png"
#     icon_size: 48 # min:48, max:256, default: 48
